name: use variables
jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Set Environment Variables
      uses: ./.github/actions/setvars
      with:
        varFilePath: ./.github/variables/myvars.env
